app = "fastapi-ytdlp"
primary_region = "mia"

[build]
  dockerfile = "Dockerfile"

[env]
  CACHE_TTL = "300"
  LOG_LEVEL = "INFO"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
